import json
from datetime import datetime

def generate_report(research_data, design_data, copy_data, event_details):
    report = f"""# 🎓 Event Plan: {event_details.get('event_type', 'Event').title()}

> Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
> Budget: ${event_details.get('budget', 'TBD')} | Location: {event_details.get('location', 'TBD')} | Guests: {event_details.get('guest_count', 'TBD')}

---

## 📍 Venue Recommendations
"""
    
    venues = research_data.get("venues", [])
    if venues:
        for i, v in enumerate(venues[:3], 1):
            report += f"""
### {i}. {v.get('title', 'Venue Name')}
- Info: {v.get('snippet', 'No details')[:120]}...
- Link: {v.get('url', '#')}
"""
    else:
        report += "*No venues found.*\n"
    
    report += f"""
---

## 🎨 Visual Theme: {design_data.get('theme_name', 'Theme')}

Description: {design_data.get('description', '')}

Color Palette:
"""
    for color in design_data.get('color_palette', []):
        report += f"- {color}\n"
    
    report += f"""
Layout Idea: {design_data.get('layout_suggestion', '')}
Vibe: {', '.join(design_data.get('mood_keywords', []))}

---

## ✉️ Invitation Text

{copy_data.get('invitation', '')}

## 🎤 MC Script

{copy_data.get('mc_script', '')}

## 📱 Social Posts

- Instagram: {copy_data.get('social_posts', {}).get('instagram', '')}
- Twitter: {copy_data.get('social_posts', {}).get('twitter', '')}
- LinkedIn: {copy_data.get('social_posts', {}).get('linkedin', '')}

---

## 💰 Budget Breakdown

| Category | Cost |
|----------|------|
| Venue | ${int(event_details.get('budget', 3000) * 0.40)} |
| Food | ${int(event_details.get('budget', 3000) * 0.30)} |
| Decor | ${int(event_details.get('budget', 3000) * 0.15)} |
| Backup | ${int(event_details.get('budget', 3000) * 0.15)} |
| **TOTAL** | **${event_details.get('budget', 3000)}** |

---

## ✅ Checklist
- [ ] Book venue
- [ ] Send invitations
- [ ] Order decor
- [ ] Post on social media
- [ ] Print MC script

---
Generated by Event Planning Assistant
"""
    
    return report


if __name__ == "__main__":
    print("📦 Testing Packaging Agent...\n")
    
    mock_research = {
        "venues": [
            {"title": "Austin Tech Hub", "snippet": "Modern space with projectors", "url": "https://example.com"}
        ]
    }
    mock_design = {
        "theme_name": "Cyberpunk College Fest",
        "description": "Futuristic neon theme",
        "color_palette": ["#00F5FF", "#FF00FF", "#000000"],
        "layout_suggestion": "Stage center, booths on sides",
        "mood_keywords": ["futuristic", "energetic"]
    }
    mock_copy = {
        "invitation": "You're invited to Cyberpunk Fest! Join us for 48 hours of innovation.",
        "mc_script": "Welcome everyone! Let's begin the show.",
        "social_posts": {
            "instagram": "#CyberpunkFest",
            "twitter": "Tech fest is coming!",
            "linkedin": "Annual college tech fest"
        }
    }
    mock_details = {
        "event_type": "college tech fest",
        "budget": 3000,
        "location": "Austin, TX",
        "guest_count": 150
    }
    
    report = generate_report(mock_research, mock_design, mock_copy, mock_details)
    print(report)
    print("\n✅ Test complete!")